service: sls-backend-culqi-tokenization
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    BEARER_TOKEN: pk_test_LsRBKejzCOEEWOsw
    MONGO_URI: mongodb+srv://db_user_alipac:yZIJZmlKJKU7w3dl@cluster0.civgv.mongodb.net/?retryWrites=true&w=majority
  apiGateway:
    description: sls-backend-culqi-tokenization-${self:provider.stage}
  iam:
    role:
      name: sls-backend-culqi-tokenization-role-${self:provider.stage}
      path: /sls-backend-culqi-tokenization-role-${self:provider.stage}/

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

functions:
  saveCard:
    handler: lambda/saveCard.handler
    name: saveCard-${self:provider.stage}
    memorySize: 128 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: card
          method: post

  getCard:
    handler: lambda/getCard.handler
    name: getCard-${self:provider.stage}
    memorySize: 128 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: card
          method: get
          request:
            parameters:
              querystrings:
                token: true
