service: reto-tecnico
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: ${opt:stage, 'desa'}
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  apiGateway:
    description: reto - tecnico - api - ${self:provider.stage}
  iam:
    role:
      name: reto-tecnico-role-${self:provider.stage}
      path: /reto-tecnico-role-${self:provider.stage}/

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  tableName: tbl_tokenizacion_${self:provider.stage}

functions:
  simularTokenizacion:
    handler: ./src/controller/TarjetaController.simularTokenizacion
    name: simularTokenizacion
    memorySize: 128 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: token
          method: post
          request:
            schemas:
              application/json: ${file(./src/request/SimularTokenizacionRequest.json)}
  
  obtenerTarjeta:
    handler: ./src/controller/TarjetaController.obtenerTarjeta
    name: obtenerTarjeta
    memorySize: 128 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: tarjeta
          method: get
          request:
            parameters:
              querystrings:
                token: true

resources:
  Resources:
    TblTokenizacion:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: fecha_expiracion
          Enabled: true 
